### PR TITLE
Fix Porgressbar rendering Checkbox (Fixes #1626)

### LINKED ISSUE #1626: Fix Porgressbar rendering Checkbox
https://github.com/lycheeverse/lychee/pull/1623#issuecomment-2639918202

```
1/1 ━━━━━━━━━━━━━━━━━━━  - [ ] [200] https://wiki.debian.org/pmount    
```

use the default OutputMode instead

### PR DESCRIPTION
**Pull request by Arteiii**
Fixed the checkbox rendering in the progressbar and the checkbox not working in no color mode.

couldn't think of a better looking formatter for the progressbar, maybe someone else has an idea LMK

### CODE REVIEW

File: lychee-bin/src/commands/check.rs [hunk 1]
```diff
@@ -66,7 +67,13 @@ where
...
     ));
 
-    let formatter = get_response_formatter(&params.cfg.mode);
+    let formatter_default = OutputMode::default();
+
+    let formatter = get_response_formatter(if matches!(params.cfg.mode, OutputMode::Task) {
+         &formatter_default
+    } else {
+        &params.cfg.mode
+    });
```
Comment (mre) [inline lychee-bin/src/commands/check.rs:76]: Maybe we can add a comment here about why this is needed?

File: lychee-bin/src/formatters/mod.rs [hunk 2]
```diff
@@ -31,7 +31,10 @@ pub(crate) fn get_stats_formatter(
 /// Create a response formatter based on the given format option
 pub(crate) fn get_response_formatter(mode: &OutputMode) -> Box<dyn ResponseFormatter> {
     if !supports_color() {
-        return Box::new(response::PlainFormatter);
+        return match mode {
+            OutputMode::Task => Box::new(response::TaskFormatter),
+            _ => Box::new(response::PlainFormatter),
+        };
```
Comment (mre) [inline lychee-bin/src/formatters/mod.rs:37]: I'm curious what's the reason for that. 😅

Comment (Arteiii) [reply lychee-bin/src/formatters/mod.rs:37]: If the terminal doesn't support colour (or [NO_COLOR](https://no-color.org/)), the task formatter will not be used, but the plaintext formatter...

Comment (Arteiii) [reply lychee-bin/src/formatters/mod.rs:37]: And since Task Formatter does not use ANSI codes...

File: lychee-bin/src/commands/check.rs [hunk 3]
```diff
@@ -66,7 +67,17 @@ where
         accept,
     ));
 
-    let formatter = get_response_formatter(&params.cfg.mode);
+    // fixes bad rendering of some formatters
```
Comment (mre) [inline lychee-bin/src/commands/check.rs:70]:
```suggestion
    // Set the default formatter for progress bar output
```

File: lychee-bin/src/commands/check.rs [hunk 4]
```diff
@@ -66,7 +67,17 @@ where
...
+    let formatter_default = OutputMode::default();
+
+    // making it easier to add new formatters in the future (without breaking progress bar)
```
Comment (mre) [inline lychee-bin/src/commands/check.rs:73]:
```suggestion
    // Make it easier to add new formatters in the future (without breaking the progress bar)
```

File: lychee-bin/src/formatters/mod.rs [hunk 5]
```diff
@@ -30,8 +30,13 @@ pub(crate) fn get_stats_formatter(
 
 /// Create a response formatter based on the given format option
 pub(crate) fn get_response_formatter(mode: &OutputMode) -> Box<dyn ResponseFormatter> {
+    // checks if color is supported in current environment or NO_COLOR is set (https://no-color.org)
```
Comment (mre) [inline lychee-bin/src/formatters/mod.rs:33]:
```suggestion
    // Checks if color is supported in current environment or NO_COLOR is set (https://no-color.org)
```

File: lychee-bin/src/formatters/mod.rs [hunk 6]
```diff
@@ -30,8 +30,13 @@ pub(crate) fn get_stats_formatter(
...
     if !supports_color() {
-        return Box::new(response::PlainFormatter);
+        // To Fix TaskFormatter not working if color is not supported
```
Comment (mre) [inline lychee-bin/src/formatters/mod.rs:35]:
```suggestion
        // To fix `TaskFormatter` not working if color is not supported
```

**Review by mre — APPROVED** [review]

**Comment by mre** [comment]
Thanks @Arteiii 👍
