### PR TITLE
fix(cache): never cache errors on disk (#1734)

### LINKED ISSUE #1734: Option to exclude failed requests from cache
The cache is incredibly helpful to reduce repetitive URL checks when running `lychee` e.g. on PR and push events from GitHub Actions, also reducing the risk to run into rate limiting. We do the following:
```yml
    - uses: actions/cache/restore@v4
      with:
        path: .lycheecache
        key: lycheecache-${{ github.run_id }}
        restore-keys: lycheecache-

    - run: ./lychee --cache --max-cache-age 2d --cache-exclude-status '201..'


    - uses: actions/cache/save@v4
      if: always()
      with:
        path: .lycheecache
        key: lycheecache-${{ github.run_id }}
```
This makes use of the GitHub Actions cache action, split into dedicated restore and save steps, so that it can be configured to save the cache as well on URL check failures.

Entries older than 2 days are ignored, of course this could be well increased.

What I try to achieve with the exclude is to assure that any previously failed request is checked again, instead of the failed result taken from cache. Especially when running into rate limits or temporary network issues at any side, a rerun can often turn things to green. Excluding HTML response codes from 201 upwards however works only if there actually was any response. In case of network errors, there is no code, and the field in the cache file is empty, no way to exclude (AFAIK). Also in case the fragment check fails, the cache entry contains an empty response code.

Hence it would be great to have a way to exclude empty HTTP response codes due to network errors from cache as well.

Optionally, some short code `failed` or something, to exclude all cache entries which would be treated as failure, depending on `--accept` as well, could be handy. I think it is the most common use case, to not check functional links in short repetition, but allow to recheck failed ones with the same workflow. But it does not replace the empty response exclusion. E.g. we accept `429` as well, the GitHub rate limit response, needed since GitHub tokens work for `api.github.com`, but not for `github.com`, and we have a LOT of GitHub repo, wiki and profile URLs in our documentation website. However, running the check multiple times, caching 200 responses, but checking 429 ones again, allows lychee to get 200 responses from all GitHub URLs at some point. Not an awesome solution, but it works well enough.

### LINKED ISSUE #1783: --cache-exclude-status can't exclude failures that have no status code
Given a file with the following unresolveable domain name:

```
https://llkalsaslasdbasdbasdb.google.com
```

And having lychee configured to ignore error status when caching via

```toml
cache_exclude_status = [
    "..100",
    "104..200",
    "300..600",
]
```

I get the following error

```
   [ERROR] https://llkalsaslasdbasdbasdb.google.com/ | Network error: error sending request for url (https://llkalsaslasdbasdbasdb.google.com/) Maybe a certificate error?
```
And the following cache entry
```
❯ cat .lycheecache | grep llkalsaslasdbasdbasdb
https://llkalsaslasdbasdbasdb.google.com/,,1754564166
```

As there is no status code returned, there is currently no way to exclude these error from being cached.

lychee should provide a way to ignore these failures, too.

(I tried to use the empty string in cache_exclude_status, but that fails when the config is parsed)

### LINKED ISSUE #2190: --cache-exclude-status doesn't cover network-level errors (connection reset, timeout); transient errors get cached indefinitely
### Problem

`--cache-exclude-status` lets you exclude HTTP status codes (e.g. `429`, `500..599`) from being cached, but network-level errors — `Connection reset by peer`, DNS failures, timeouts that never get an HTTP response — have no status code and cannot be excluded. Lychee caches them with `--cache` just like any other result.

On a subsequent run lychee finds the cached error, considers it fresh (within `--max-cache-age`), and reports the failure without retrying — bypassing `--max-retries` entirely. A transient infrastructure blip in one run thus causes every subsequent run that uses the cache to fail on a URL that is actually healthy.

### Reproduction

1. Run lychee with `--cache` against a URL that has a flaky network path.
2. On the first run where the connection is reset, lychee caches the error.
3. On any subsequent run within `--max-cache-age`, lychee immediately reports the URL as failed without making a network request (and without applying `--max-retries`).

### Expected behaviour

Network-level errors should not be cached, or at minimum should be excludable. They are inherently transient — unlike a `404` (the page is gone) or a `403` (access denied), a TCP reset or DNS timeout says nothing about the long-term availability of the URL.

### Proposed fix

One or both of the following:

1. **Extend `--cache-exclude-status`** to accept a sentinel value such as `error` or `network` that matches any non-HTTP failure (connection reset, timeout with no response, DNS error, etc.).
   Example: `--cache-exclude-status error,429,500..599`

2. **Default to not caching network errors.** HTTP `404`/`410` are worth caching (the resource is gone). A TCP reset is not — it almost certainly reflects a transient condition. Caching it by default makes \`--max-retries\` useless for cached runs.

### Workaround

Strip non-2xx entries from the restored \`.lycheecache\` file before invoking lychee. This forces lychee to re-check any URL that previously errored, restoring proper retry behaviour regardless of what is in the cache:
```bash
# Keep only successful cache entries so transient errors are always retried
if [ -f .lycheecache ]; then
  grep -E ',2[0-9]{2},' .lycheecache > .lycheecache.tmp || true
  mv .lycheecache.tmp .lycheecache
fi
```
Note: this relies on the assumption that lychee's cache format stores the HTTP status as a comma-delimited field — if the format changes this workaround will silently drop all cache entries. A first-class flag in lychee is the right fix.

### PR DESCRIPTION
**Pull request by mre**
After thinking about this for a while, I think caching errors goes against typical CI workflows.

That's because if a link fails due to a network issue, a server outage, or if a previously failing link has been fixed, reading an error from the cache prevents lychee from realizing the link is now working. Right now it will load the broken link from cache, notice that it has no status code associated with it, and fail immediately. It just caches the error again until it expires and gets re-checked. That's quite unintuitive.

This commit updates Cache::store and Cache::load to skip CacheStatus::Error. As a result, failures are always rechecked on subsequent runs. We completely sidestep issues with caching transient network errors or missing HTTP status codes.

Fixes #1734.
Fixes #1783.
Fixes #2190.

### CODE REVIEW

File: lychee-bin/tests/cli.rs [hunk 1]
```diff
@@ -1601,8 +1601,7 @@ The config file should contain every possible key for documentation purposes."
         // If the status code was 999, the cache file should be empty
         // because we do not want to cache unknown status codes
         let buf = fs::read(&cache_file).unwrap();
-        let data = String::from_utf8(buf)?;
-        assert!(data.contains(",999,"));
+        assert!(buf.is_empty(), "cache file should be empty, but was {}", String::from_utf8_lossy(&buf));
```
Comment (mre) [inline lychee-bin/tests/cli.rs]: It looks like the mock server from #2019 made the `999` error cacheable, so this assertion was flipped to make the test pass (even though the comment above it still declared "the cache file should be empty" 😉). Since we're no longer caching errors at all, the code finally matches the prophecy!

File: lychee-bin/tests/cli.rs [hunk 2]
```diff
@@ -1454,8 +1454,10 @@ The config file should contain every possible key for documentation purposes."
         // check content of cache file
         let data = fs::read_to_string(&cache_file)?;
         assert!(data.contains(&format!("{}/,200", mock_server_ok.uri())));
-        assert!(data.contains(&format!("{}/,418", mock_server_teapot.uri())));
-        assert!(data.contains(&format!("{}/,500", mock_server_server_error.uri())));
+        // Because the first run DID NOT use `--accept`, 418 and 500 were both treated as errors.
+        // With our new error dropping logic, NEITHER gets cached in the first run.
+        assert!(!data.contains(&format!("{}/,418", mock_server_teapot.uri())));
+        assert!(!data.contains(&format!("{}/,500", mock_server_server_error.uri())));
```
Comment (mre) [inline lychee-bin/tests/cli.rs:1460]: A consequence of this is that we will cache way fewer things in the future, including error status codes which were cached prior. The alternative is that we always cache responses with a status code.

But I think the change is fine, and our logic was flawed from the beginning.

The reason is that when someone uses the lychee --cache feature, its entire purpose is essentially: "Save me time and bandwidth by not checking URLs that I already know are good." 

If we cache failures (even ones with valid HTTP status codes like 404 or 500), we introduce a paradox: We are actively preventing lychee from discovering when a link gets fixed! If you merge a PR that fixes a broken link on your website, but your CI system restores the .lycheecache from the main branch, lychee will loudly fail your pipeline because the cache says 404 Error (cached) and refuses to check the now-working link until max-cache-age expires. :(

If we explicitly only cached errors that have status codes, we'd still experience that same painful workflow issue where users are forced to manually clear .lycheecache to get their pipeline to pass after fixing a link. 

In my opinion, caching should strictly mean only caching successful states. We should always re-evaluate failures just in case they're fixed now. (Can't think of any exception right now, but I might be missing something. Please let me know.)

When you couple this with the fact that lychee deduplicates URLs per-run anyway (so a single run won't spam a failing host 500 times for the same broken link), dropping all errors from the persistent disk cache is the best path forward IMHO.

Does that philosophy make sense or am I missing something?

Comment (thomas-zahner) [reply lychee-bin/tests/cli.rs:1460]: I totally agree, and I don't see any problems with the current implementation. As your test shows, I don't see how this could break compatibility with "old" cache files. So I think this change does make sense and is an improvement.

**Review by thomas-zahner — APPROVED** [review]

**Comment by guettli** [comment]
@mre thank you very much for that PR. When will be the next release, containing this change?

**Comment by mre** [comment]
Should be very soon.
