### PR TITLE
Accept ranges

### LINKED ISSUE #1769: `--accept` doesn't accept the same values as `--cache-exclude-status`
>       --cache-exclude-status <CACHE_EXCLUDE_STATUS>
>           A list of status codes that will be ignored from the cache
> 
>           The following exclude range syntax is supported: [start]..[[=]end]|code. Some valid
>           examples are:
> 
>           - 429 (excludes the 429 status code only)
>           - 500.. (excludes any status code >= 500)

looks like this should work

```shell-session
$ lychee -- --config tools/lychee/config.toml --cache --cache-exclude-status '500..' .
warning: Git tree '/home/katexochen/edgelesssys/contrast' is dirty
error: invalid value '500..' for '--cache-exclude-status <CACHE_EXCLUDE_STATUS>': failed to parse accept range: no range pattern found

For more information, try '--help'.
error: Recipe `check-links` failed on line 385 with exit code 2

$ lychee -- --version
lychee 0.18.1
```

### PR DESCRIPTION
**Pull request by thomas-zahner**
Fixes #1769. Previously `lychee example.com --accept 123..` lead to `Error: invalid status code`.

In the process I've eliminated some primitive obsession with `u16` where we actually meant `StatusCode`. This also improved error handling with invalid values in the lychee cache file. See commit messages for more information.

Improves the error messages overall. For example prviously:

`error: invalid value '123..1234' for '--cache-exclude-status <CACHE_EXCLUDE_STATUS>': failed to parse accept range: no range pattern found`

Now:

`error: invalid value '123..1234' for '--cache-exclude-status <CACHE_EXCLUDE_STATUS>': failed to parse range: values must represent valid status codes between 100 and 999 (inclusive)`

### CODE REVIEW

File: lychee-lib/src/types/accept/range.rs [hunk 1]
```diff
@@ -1,10 +1,20 @@
...
 
+/// Smallest accepted value
+const MIN: u16 = 100;
+
+/// Biggest accepted value
+const MAX: u16 = 999;
+
 static RANGE_PATTERN: LazyLock<Regex> =
-    LazyLock::new(|| Regex::new(r"^([0-9]{3})?\.\.((=?)([0-9]{3}))?$|^([0-9]{3})$").unwrap());
+    LazyLock::new(|| Regex::new(r"^([0-9]+)?\.\.((=?)([0-9]+))?$|^([0-9]+)$").unwrap());
```
Comment (thomas-zahner) [inline lychee-lib/src/types/accept/range.rs]: This is for better error messages, so that we can yield `InvalidStatusCodeValue`

File: lychee-lib/src/types/accept/range.rs [hunk 2]
```diff
@@ -21,117 +31,114 @@ pub enum AcceptRangeError {
...
+            Self::new(value, value)
         } else {
             let start: u16 = match captures.get(1) {
                 Some(start) => start.as_str().parse().unwrap_or_default(),
-                None => 0,
+                None => MIN,
             };
             if captures.get(2).is_none() {
-                return Self::new_from(start, u16::MAX);
+                return Self::new(start, MAX);
```
Comment (thomas-zahner) [inline lychee-lib/src/types/accept/range.rs:69]: This is the bugfix with the `123..` example, it now ends at 999

**Comment by thomas-zahner** [comment]
@HadrienG2 & @katrinafyi feel free to take a look and review

File: lychee-lib/src/types/accept/range.rs (hunk 1 above)
Comment (katrinafyi) [reply lychee-lib/src/types/accept/range.rs]: I'd comment the regex, outlining the cases it's meant to cover and labelling each group number. 

_optionally_, I personally try very hard to avoid regex - it could be a string split and manual processing. but I think the complexity is just enough for a regex too

File: lychee-lib/src/types/accept/range.rs [hunk 3]
```diff
@@ -21,117 +31,114 @@ pub enum AcceptRangeError {
     /// The start index is larger than the end index.
     #[error("invalid range indices, only start < end supported")]
     InvalidRangeIndices,
+
+    /// The u16 values must be representable as status code
+    #[error("values must represent valid status codes between 100 and 999 (inclusive)")]
```
Comment (katrinafyi) [inline lychee-lib/src/types/accept/range.rs]: any chance of using the constants to make this string, rather than hard coding?

File: lychee-lib/src/types/accept/range.rs (hunk 1 above)
Comment (thomas-zahner) [reply lychee-lib/src/types/accept/range.rs]: > I personally try very hard to avoid regex

I like this mindset :) But I think I won't change it in this PR. It's well tested so that we know it works as expected but I agree that regex is often not the best way. I've documented it by using named capture groups in 45e54fea

File: lychee-lib/src/types/accept/range.rs (hunk 3 above)
Comment (thomas-zahner) [reply lychee-lib/src/types/accept/range.rs]: Great idea, was easier than expected. 45e54fea

File: lychee-lib/src/types/cache.rs [hunk 4]
```diff
@@ -37,15 +64,24 @@ impl<'de> Deserialize<'de> for CacheStatus {
...
+                        // classify successful status codes as cache status success
+                        // Does not account for status code overrides passed through
+                        // the 'accept' flag. Instead, this is handled at a higher level
+                        // when the cache status is converted to a status.
+                        Ok(CacheStatus::Ok(code))
+                    } else {
+                        // classify redirects, client errors, & server errors as cache status error
+                        Ok(CacheStatus::Error(Some(code)))
+                    }
+                }
```
Comment (mre) [inline lychee-lib/src/types/cache.rs:84]: Nicely done

**Comment by mre** [comment]
image

Superb job and much cleaner. Neat!
