### PR TITLE
fix: do not fail on empty # and #top fragments

### LINKED ISSUE #1599: Always succeed empty fragment checks
Currently we see errors like
```
file:///home/runner/work/repo/path/to/stats.html# | Failed: Cannot find fragment
```
while the empty fragment `#` is well known to scroll to the top of the page, just like `#top`, while the latter can be overwritten, if there is an HTML element with `id="top"`. I suggest to succeed the fragment check right away if any of those two special fragments is found.

Sadly I could not find a good source in RFCs or similar. Maybe it is just browsers implementing this outside of specs. The empty fragment is very widely used, the `#top` however I found just now, while searching for a related source. It works however well in all browsers I checked: https://stackoverflow.com/a/77560206

### PR DESCRIPTION
**Pull request by MichaIng**
The empty "#" and "#top" fragments are always valid without related HTML element. Browser will scroll to the top of the page. Hence lychee must not fail on those.

Fixed #1599

### CODE REVIEW

**Comment by MichaIng** [comment]
Went with the two `==` first, but lint suggests `is_empty()`. The two test runs show the currently inconsistent results:
1. https://github.com/lycheeverse/lychee/actions/runs/12665712696/job/35295837656
    `#top` in `file.html` succeeds, `#` in `file.html` and `#` + `#top` in  `file1.md` fail.
2. https://github.com/lycheeverse/lychee/actions/runs/12665772582/job/35296001037
    `#` in `file.html` succeeds, `#top` in `file.html` and `#` + `#top` in  `file1.md` fail.

On my local tests, randomly, at least one, up to all of those failed. Would be interesting to know where this inconsistency is coming from, as I would suggest the same fragment to succeed or fail every time the same way 🤔.

**Comment by thiru-appitap** [comment]
[updated my findings, the resolution and test information in here](https://github.com/lycheeverse/lychee/issues/1599#issuecomment-2585926737)

please let me know if this works.

**Comment by MichaIng** [comment]
Awesome, the embarrassingly missed empty/top fragment handling in case of existing cache entry was the solution 👍. The redundant `map_or` is unrelated to this PR.

File: lychee-lib/src/utils/fragment_checker.rs [hunk 1]
```diff
@@ -59,19 +59,20 @@ impl FragmentChecker {
...
                 let file_frags = extractor(&content);
                 let contains_fragment =
                     file_frags.contains(fragment) || file_frags.contains(&fragment_decoded as &str);
                 entry.insert(file_frags);
-                Ok(contains_fragment)
-            }
-            Entry::Occupied(entry) => {
-                Ok(entry.get().contains(fragment)
-                    || entry.get().contains(&fragment_decoded as &str))
+                Ok(is_emtpty_or_top_fragment || contains_fragment)
```
Comment (MichaIng) [inline lychee-lib/src/utils/fragment_checker.rs:71]: Probably Rust optimises such automatically, but in code logic, it does not make sense to check first whether the fragment is contained, if it is empty or `top`. So instead of creating `contains_fragment`, it could be better in terms of performance/logic to align it with below, to skip `contains_fragment =` and instead do:
```suggestion
                Ok(is_emtpty_or_top_fragment
                    || file_frags.contains(fragment)
                    || file_frags.contains(&fragment_decoded as &str))
```

Comment (MichaIng) [reply lychee-lib/src/utils/fragment_checker.rs]: Ah no, that does not work since `file_frags` is moved by `insert`. Another approach, insert it if missing, and check the cache entry in any case afterwards.

Comment (MichaIng) [reply lychee-lib/src/utils/fragment_checker.rs]: Now it is checked and returned much earlier, if the fragment is empty or "top". No point to further process the fragment and URL, create or check the cache entry etc. Those cases can be handled just the same way as if there was no fragment at all.

Comment (thiru-appitap) [reply lychee-lib/src/utils/fragment_checker.rs]: @MichaIng 
yes, indeed - this is a much better option (I'll start to to look from these perspectives too - thank you!)

one quick observation - by exiting earlier, we're postponing the extraction operation (to later) and thereby the cache updates - I don't see it creating any issues but wanted to note it here.

Comment (MichaIng) [reply lychee-lib/src/utils/fragment_checker.rs]: Yeah I was also thinking about the skipped/delayed cache entry, but it actually makes sense:
- Either the same URL is not checked with any other fragment later, then the cache entry is now skipped. It would have remained unused anyway.
- Or the same URL is checked with another fragment later, then the cache entry is created at this later point, which does not cause any downside.

**Comment by mre** [comment]
@MichaIng, sorry, I dropped the ball on that one. What's the current status on this?
I can see some lint issues, but they seem to be unrelated. Anything else or is this ready to be merged?

**Comment by MichaIng** [comment]
@mre
It is ready to go. The `map_or` redundancy annotation of clippy is unrelated and probably just due to a clippy update: https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
So
```ru
.map_or(false, ...
```
to
```ru
.is_some_and(...
```
seems sane. But in a dedicated PR I suggest.

**Comment by mre** [comment]
@MichaIng, can you rebase on top of `master`? I just fixed the clippy lint issues (https://github.com/lycheeverse/lychee/pull/1625). That should make the build green.
