### PR TITLE
Cache verbosity issue (fixes #562)

### LINKED ISSUE #562: v0.9.0 regression: Unknown schemes throw errors
We have some code blocks in our docs which contain schemes unknown to lychee but valid for other applications. Those were gracefully ignored before and now throw errors, e.g.:
```
Error: R] librespot:///usr/bin/librespot?name=mySpotify&devicename=SnapcastSpotify&disable_audio_cache=true | The given URI is invalid: librespot:///usr/bin/librespot?name=mySpotify&devicename=SnapcastSpotify&disable_audio_cache=true
Error: R] pipe:///tmp/mpd.fifo?name=myMPD&mode=read | The given URI is invalid: pipe:///tmp/mpd.fifo?name=myMPD&mode=read
Error: R] airplay:///usr/local/bin/shairport-sync?name=myAirport&devicename=SnapcastAirport&params=--configfile=/usr/local/etc/shairport-sync.conf | The given URI is invalid: airplay:///usr/local/bin/shairport-sync?name=myAirport&devicename=SnapcastAirport&params=--configfile=/usr/local/etc/shairport-sync.conf
Error: R] pipe:///tmp/mopidy.fifo?name=myMopidy&mode=read | The given URI is invalid: pipe:///tmp/mopidy.fifo?name=myMopidy&mode=read
```
Since lychee anyway catches those URLs by itself, while they are no explicit links, it doesn't make much sense to fail on them: "This looks like an URL, let me check it... but doesn't look like a valid URL, let me throw an error" 😃.

### PR DESCRIPTION
**Pull request by mre**
Don't print cached status output when not in verbose mode

### CODE REVIEW

File: lychee-bin/src/commands/check.rs [hunk 1]
```diff
@@ -155,10 +156,33 @@ fn show_progress(
             pb.println(out);
         }
     } else {
-        if (response.status().is_success() || response.status().is_excluded()) && !verbose {
+        if !verbose && (response.status().is_success() || response.status().is_excluded()) {
```
Comment (lebensterben) [inline lychee-bin/src/commands/check.rs:159]: It's more idiomatic to write

if verbose || !(response.status.is_success() || response.status.is_excluded()) {
    // print
}

Comment (mre) [reply lychee-bin/src/commands/check.rs:159]: To be honest I don't like any version so far. It's easy to get wrong.
For example, the correct expression of your version sould be 
```rust
if verbose || !(response.status().is_success() && response.status().is_excluded())
```
(There needs to be `&&` between success and excluded`.)


What do you think about splitting it up?

```rust
if !verbose {
    if response.status().is_success() || response.status().is_excluded() {
        return Ok(());
    }
}
        ```

Comment (mre) [reply lychee-bin/src/commands/check.rs]: Super opinionated, but I honestly like the the two if conditions the easiest to reason about &mdash; it's just that clippy didn't like it. I experimented a bit but couldn't come up with anything that doesn't make my head spin, so I added a clippy exception for this single case.
We should probably refactor that part anyway at some point. 😉

Comment (mre) [reply lychee-bin/src/commands/check.rs]: Will merge this now. We can revisit this at some point if we want to change it. At least the logic should be correct now and we have a unit test for the correct behavior. This should make future refactoring easier.

Comment (lebensterben) [reply lychee-bin/src/commands/check.rs]: my point is to eliminate a local return here.

So instead of (if condition return else print), it's much better to have (if condition print else ok)

Comment (MichaIng) [reply lychee-bin/src/commands/check.rs]: It could be even merged with the `} else {` into an `} else if ... {`:
```ru
    } else if verbose || !(response.status().is_success() || response.status().is_excluded()) {
        writeln!(output, "{out}")?;
    }
    Ok(())
```
The second `||` is correct here instead of `&&`. Probably better to understand:
```ru
    } else if verbose || (!response.status().is_success() && !response.status().is_excluded()) {
        writeln!(output, "{out}")?;
    }
    Ok(())
```
"Print if either verbose, or not successful and not excluded."

Comment (mre) [reply lychee-bin/src/commands/check.rs]: Sure we can change it. Would you be interested in creating a pull request? It's not high priority, though.
