### PR TITLE
Harden URL detection and extend verbatim elements

### LINKED ISSUE #895: algolia search box troubles?
Hello,
Can We do something with results from pages containing algolia search box ? Thanks
```
➜  /tmp ./lychee https://www.algolia.com/search/
⠐ 31/31 [00:00:10] █████████████████████████ ✗ [400] https://res.cloudinary.com/hilnmyskv/image/upload/v1580296397/Algolia_com_Website_assets/logo-algolia-xenon-blue-full.png&quot | FailedIssues found in 1 input. Find details below.

[https://www.algolia.com/search/]:
✗ [404] https://1qdawl72tq-dsn.algolia.net/ | Failed: Network error: Not Found
✗ [400] https://cdn.cookielaw.org/ | Failed: Network error: Bad Request
✗ [404] https://www.facebook.com/algolia/&quot | Failed: Network error: Not Found
✗ [404] https://www.instagram.com/algoliahq/&quot | Failed: Network error: Not Found
✗ [400] https://res.cloudinary.com/hilnmyskv/image/upload/v1580296397/Algolia_com_Website_assets/logo-algolia-xenon-blue-full.png&quot | Failed: Network error: Bad Request
✗ [404] https://cdn.segment.com/analytics.js/v1/ | Failed: Network error: Not Found
✗ [404] https://www.algolia.com/contact/enterprise/&quot | Failed: Network error: Not Found
✗ [404] https://www.algolia.com/demorequest/&quot | Failed: Network error: Not Found
✗ [404] https://www.github.com/Algolia/&quot | Failed: Network error: Not Found
✗ [404] https://res.cloudinary.com/ | Failed: Network error: Not Found
✗ [404] https://www.algolia.com/for-open-source/&quot | Failed: Network error: Not Found
✗ [404] https://www.twitter.com/Algolia/&quot | Failed: Network error: Not Found
✗ [400] https://res.cloudinary.com/hilnmyskv/image/upload/v1527077656/Algolia_OG_image_m3xgjb.png&quot | Failed: Network error: Bad Request
✗ [404] https://www.algolia.com/&quot | Failed: Network error: Not Found

🔍 31 Total ✅ 16 OK 🚫 14 Errors (HTTP:14) 💤 1 Excluded
```

lychee v0.10.3

### PR DESCRIPTION
**Pull request by mre**
Previously remote URLs were incorrectly detected because the
string representation of a path is different than the path itself,
causing the `http` prefix match to be insufficient.

This resulted in unexpected side-effects, such as the
incorrect detection of verbatim mode for remote URLs.

The check now got improved and unit tests were added to avoid
future breakage. On top of that, missing verbatim elements were added.

Fixes #895.

### CODE REVIEW

File: lychee-lib/src/extract/mod.rs [hunk 1]
```diff
@@ -17,7 +17,18 @@ use plaintext::extract_plaintext;
 pub(crate) fn is_verbatim_elem(name: &str) -> bool {
     matches!(
         name,
-        "code" | "listing" | "plaintext" | "samp" | "script" | "textarea" | "xmp" | "pre"
+        "address"
```
Comment (lebensterben) [inline lychee-lib/src/extract/mod.rs:20]: per https://html.spec.whatwg.org/#the-address-element

`address` elements is not really verbatim as it may contain other tags. in particular, it may contain hyperlinks such as in the example:

```html
<footer>
 <address>
  For more details, contact
  <a href="mailto:js@example.com">John Smith</a>.
 </address>
 <p><small>© copyright 2038 Example Corp.</small></p>
</footer>
```

File: lychee-lib/src/extract/mod.rs [hunk 2]
```diff
@@ -17,7 +17,18 @@ use plaintext::extract_plaintext;
...
+            | "code"
+            | "kbd"
+            | "listing"
```
Comment (lebensterben) [inline lychee-lib/src/extract/mod.rs:23]: what is `listing` here? there is no `<listing>` tag.
P.S. I also cannot find the test case for it.

Comment (mre) [reply lychee-lib/src/extract/mod.rs:23]: It's obsolete. Didn't add a unit test because of that. It got entirely replaced by `pre` and `code` but there might be older sites out there which still use it.

File: lychee-lib/src/extract/mod.rs (hunk 1 above)
Comment (mre) [reply lychee-lib/src/extract/mod.rs:20]: Good point. Will remove, thanks!

Comment (mre) [reply lychee-lib/src/extract/mod.rs:20]: https://github.com/lycheeverse/lychee/pull/901
