### PR TITLE
Replace unmaintained human-sort with numeric-sort

### LINKED ISSUE #1758: Switch to `numeric-sort`
[human-sort is unmaintained.](https://github.com/paradakh/human-sort/issues/5#issuecomment-2429487512)

It's also broken in recent Rust versions. I found out when checking a bunch of links:

```rust
 lychee links.txt
  178/178 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links
thread 'main' panicked at library/core/src/slice/sort/shared/smallsort.rs:860:5:
user-provided comparison function does not correctly implement a total order
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```rust
❯❯❯ RUST_BACKTRACE=1 lychee links.txt
  178/178 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links
thread 'main' panicked at library/core/src/slice/sort/shared/smallsort.rs:860:5:
user-provided comparison function does not correctly implement a total order
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::sort::shared::smallsort::panic_on_ord_violation
   3: core::slice::sort::shared::smallsort::sort8_stable
   4: core::slice::sort::stable::quicksort::quicksort
   5: core::slice::sort::stable::drift::sort
   6: core::slice::sort::stable::driftsort_main
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: lychee::formatters::stats::sort_stat_map
  10: <lychee::formatters::stats::compact::Compact as lychee::formatters::stats::StatsFormatter>::format
  11: lychee::run::{{closure}}
  12: tokio::runtime::park::CachedParkThread::block_on
  13: tokio::runtime::runtime::Runtime::block_on
  14: lychee::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/t/fuzz ❯❯❯
```

The issue is [described here](https://github.com/paradakh/human-sort/issues/5).

We should switch to [numeric-sort](https://crates.io/crates/numeric-sort) instead. Pull requests welcome!

### PR DESCRIPTION
**Pull request by tosky1125**
## Description
Fixes #1758

Replaces the unmaintained `human-sort` crate with `numeric-sort` to fix panic issues in recent Rust versions.

## Problem
- `human-sort` is unmaintained
- Causes "user-provided comparison function does not correctly implement a total order" panic in recent Rust versions

## Solution
- Replace `human-sort` (0.2.2) with `numeric-sort` (0.1.5)
- Update all usages of `human_sort::compare` to `numeric_sort::cmp`
- The new crate provides the same natural/human sorting behavior

## Changes
- Updated `Cargo.toml` dependency
- Modified sorting logic in:
  - `lychee-bin/src/formatters/stats/mod.rs`
  - `lychee-bin/src/formatters/stats/compact.rs`
  - `lychee-bin/src/formatters/stats/detailed.rs`

## Testing
- [x] `cargo build` passes without errors
- [x] `cargo test` passes
- [x] No more panic when running lychee
- [x] Sorting behavior remains consistent with natural ordering

### CODE REVIEW

File: lychee-bin/src/formatters/stats/compact.rs [hunk 1]
```diff
@@ -52,7 +54,7 @@ impl Display for CompactResponseStats {
                 let mut sorted_suggestions: Vec<_> = suggestions.iter().collect();
                 sorted_suggestions.sort_by(|a, b| {
                     let (a, b) = (a.to_string().to_lowercase(), b.to_string().to_lowercase());
-                    human_sort::compare(&a, &b)
+                    cmp(&a, &b)
```
Comment (mre) [inline lychee-bin/src/formatters/stats/compact.rs]: There is [`std::cmp`](https://doc.rust-lang.org/std/cmp/index.html). Can we use the fully qualified name here to avoid the naming confusion?

```suggestion
                    numeric_sort::cmp(&a, &b)
```

File: lychee-bin/src/formatters/stats/detailed.rs [hunk 2]
```diff
@@ -68,7 +68,7 @@ impl Display for DetailedResponseStats {
                 let mut sorted_suggestions: Vec<_> = suggestions.iter().collect();
                 sorted_suggestions.sort_by(|a, b| {
                     let (a, b) = (a.to_string().to_lowercase(), b.to_string().to_lowercase());
-                    human_sort::compare(&a, &b)
+                    cmp(&a, &b)
```
Comment (mre) [inline lychee-bin/src/formatters/stats/detailed.rs]: Same here and in the other examples

**Comment by mre** [comment]
Thanks for the PR. Added some comments.

**Comment by shawneverest** [comment]
@mre 
Thanks for the review! I've updated all three files to use the fully qualified name:
- Removed `use numeric_sort::cmp;` imports
- Changed all usages to `numeric_sort::cmp(&a, &b)`

This should make it clear that we're using the numeric_sort function rather than the std module.

**Comment by mre** [comment]
Yup, that makes perfect sense. Thanks a lot!
