### PR TITLE
fix: ignore gitlab table of content in wikilinks

### LINKED ISSUE #1708: Incorrect missing "_TOC_" file errors in latest Docker images
The latest Alpine Docker image (`lycheeverse/lychee:latest-alpine`, `sha256:e5305acc0ffab80b4ee1733eb2d9667949cb9fe807f6ae39f960dccb4ba315e9`) released yesterday is incorrectly reporting errors for missing `_TOC_` files that shouldn't be causing failures, seemingly triggered by[ GitLab flavoured markdown for Table of Contents](https://docs.gitlab.com/user/markdown/#table-of-contents) being present in files.

This is causing CI builds to fail when they previously succeeded:

```
[ERROR] file:///Dev/docs/_TOC_ | Cannot find file
```

On previous Docker shas (`lycheeverse/lychee:sha-a8c0f45-alpine`) this issue is not present. This issue is present in both alpine and normal docker images.

### PR DESCRIPTION
**Pull request by JayJayArr**
fixes #1708

### CODE REVIEW

File: lychee-lib/src/extract/markdown.rs [hunk 1]
```diff
@@ -65,6 +65,10 @@ pub(crate) fn extract_markdown(input: &str, include_verbatim: bool) -> Vec<RawUr
                     // Wiki URL (`[[http://example.com]]`)
                     LinkType::WikiLink { has_pothole: _ } => {
                         inside_link_block = true;
+                        //Ignore gitlab toc notation: https://docs.gitlab.com/user/markdown/#table-of-contents
+                        if ["_TOC_".to_string(), "TOC".to_string()].contains(&dest_url.to_string()) {
+                            return None;
+                        }
```
Comment (mre) [inline lychee-lib/src/extract/markdown.rs:71]: Not sure, but have you tried

```rust
if ["_TOC_", "TOC"].contains(&dest_url.as_str()) {
```

Would save a few allocs.

**Comment by mre** [comment]
Thanks for the fix! One little thingy. 😃

File: lychee-lib/src/extract/markdown.rs (hunk 1 above)
Comment (JayJayArr) [reply lychee-lib/src/extract/markdown.rs:71]: Sounds very good!

Comment (mre) [reply lychee-lib/src/extract/markdown.rs:71]: Wow, you really did some soul-searching to dig this up. Nice research. ❤️ 
All good then.

File: lychee-lib/src/extract/markdown.rs [hunk 2]
```diff
@@ -421,4 +425,12 @@ $$
...
         assert_eq!(uris, expected);
     }
+
+    #[test]
+    fn test_ignore_gitlab_toc() {
+        let markdown = r"[[_TOC_]][TOC]";
+        let expected = vec![];
+        let uris = extract_markdown(markdown, true);
+        assert_eq!(uris, expected);
+    }
```
Comment (mre) [inline lychee-lib/src/extract/markdown.rs:435]:
```suggestion
    #[test]
    fn test_ignore_gitlab_toc() {
        let markdown = r"[[_TOC_]][TOC]";
        let uris = extract_markdown(markdown, true);
        assert!(uris.is_empty());
    }
```
